{{- if and .Values.webhook.enable -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "polaris.fullname" . }}-certificates
  {{- if .Values.templateOnly }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "polaris.fullname" . }}-webhook
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - 'secrets'
      - 'services'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
    - 'certificates.k8s.io'
    resources:
    - 'certificatesigningrequests'
    - 'certificatesigningrequests/approval'
    verbs:
    - 'get'
    - 'update'
    - 'create'
    - 'delete'
  - apiGroups:
    - 'certificates.k8s.io'
    resources:
    - 'signers'
    resourceNames:
    - 'kubernetes.io/legacy-unknown'
    verbs:
    - 'approve'
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - 'validatingwebhookconfigurations'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "polaris.fullname" . }}-webhook
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "polaris.fullname" . }}-webhook
subjects:
  - kind: ServiceAccount
    name: {{ include "polaris.fullname" . }}-certificates
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "polaris.fullname" . }}-webhook
  {{- if .Values.templateOnly }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
rules:
  # required for current controller-runtime bootstrap method
  - apiGroups:
      - ''
    resources:
      - 'secrets'
      - 'services'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "polaris.fullname" . }}-webhook
  {{- if .Values.templateOnly }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "polaris.fullname" . }}-webhook
subjects:
  - kind: ServiceAccount
    name: {{ include "polaris.fullname" . }}-certificates
    namespace: {{ .Release.Namespace }}
{{- end -}}
